version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://pl3ix5glc.bkt.clouddn.com
    ports:
      - "9008:8080"
    volumes:
      - "/docker/data/ipa-server:/app/upload"
  caddy:
    image: abiosoft/caddy:0.10.14
    restart: always
    network_mode: host
    entrypoint: |
      sh -c 'echo "$$CADDY_CONFIG" > /etc/Caddyfile && /usr/bin/caddy --conf /etc/Caddyfile --log stdout'
    environment:
      CADDY_CONFIG: |
        pl3ix5glc.bkt.clouddn.com {
          gzip
          proxy / localhost:9008
        }
